FROM ubuntu:jammy

# Install packages
ENV TZ=America/New_York
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update \
    && apt-get -yqq install \
        software-properties-common \
        curl \
        unzip

# Install older php
RUN apt-get update \
    && add-apt-repository ppa:ondrej/php \
    && apt-get -yqq install \
        php8.0 \
        php8.0-curl \
        php8.0-dev \
        php8.0-gd \
        php8.0-mbstring \
        php8.0-mysql \
        php8.0-pdo \
        php8.0-xdebug \
        php8.0-xml \
        php8.0-zip \
        php8.0-intl \
    && update-alternatives --set php /usr/bin/php8.0

# Install composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php -r "if (hash_file('sha384', 'composer-setup.php') === '55ce33d7678c5a611085589f1f3ddf8b3c52d662cd01d4ba75c0ee0459970c2200a51f492d557530c71c15d8dba01eae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" \
    && php composer-setup.php \
    && php -r "unlink('composer-setup.php');" \
    && mv composer.phar /usr/local/bin/composer
