FROM ubuntu:jammy

# Install packages
ENV TZ=America/New_York
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update \
    && apt-get -yqq install \
        software-properties-common \
        curl \
        unzip

# Install older php
RUN apt-get update \
    && add-apt-repository ppa:ondrej/php \
    && apt-get -yqq install \
        php8.2 \
        php8.2-curl \
        php8.2-dev \
        php8.2-gd \
        php8.2-mbstring \
        php8.2-mysql \
        php8.2-pdo \
        php8.2-xml \
        php8.2-zip \
        php8.2-intl \
        php8.2-xdebug \
    && update-alternatives --set php /usr/bin/php8.2

# Install composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php -r "if (hash_file('sha384', 'composer-setup.php') === 'e21205b207c3ff031906575712edab6f13eb0b361f2085f1f1237b7126d785e826a450292b6cfd1d64d92e6563bbde02') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" \
    && php composer-setup.php \
    && php -r "unlink('composer-setup.php');" \
    && mv composer.phar /usr/local/bin/composer
